#!/usr/bin/env sh
# ytools audio (interactive): search and interactively select a
# result to listen to

set -e

ytools-search $@
echo -n 'Selection [1]: '
read selection
test -z "${selection}" && selection=1
mpv --ytdl-format "bestaudio/best" --no-video "$(ytools-pick "${selection}")"
