#!/usr/bin/env sh
# ytools autoplay video: play a search result, then keep playing
# the first recommendations

mpv --ytdl-format="bestvideo[height<=?1080]+bestaudio/best" "$(ytools-pick $@)"
while true
do
	echo -n 'Next recommendation:'
	ytools-recommend | head -n1 | cut -d ':' -f '2-'
	mpv --ytdl-format="bestvideo[height<=?1080]+bestaudio/best" "$(ytools-pick 1)"
done
